# Generated by Django 3.1.2 on 2022-05-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220518_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='prid',
        ),
    ]
